package productMgmt;

import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.util.ArrayList;

public class product_line {
    
    // Inventory Employee Fields
    public int product_line_ID;
    public String product_line_name;
    public String brand;
    public Boolean isActive = true;
    public String category;
    public String product_line_description;
    
    public ArrayList product_line_IDList = new ArrayList<>();
    public ArrayList product_line_nameList = new ArrayList<>();
    public ArrayList brandList = new ArrayList<>();
    public ArrayList isActiveList = new ArrayList<>();
    public ArrayList categoryList = new ArrayList<>();
    public ArrayList product_line_descriptionList = new ArrayList<>();

       
    // Method: Registration
    public int register_product_line() {
        try {
            
            // Instantiate Connection Variable and Connect to Database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbwarehouse?useTimezone=true&serverTimezone=UTC&user=root&password=12345678");
            
            // MySQL INSERT Statement
            PreparedStatement pstmt = conn.prepareStatement("SELECT MAX(productLineID) + 1 AS newID FROM productline");
            ResultSet rst= pstmt.executeQuery();
            
            // Autogenerated Employee ID
            while(rst.next()) {
                product_line_ID = rst.getInt("newID");
            }
            
            // Assign Values
            pstmt = conn.prepareStatement("INSERT INTO productline (productLineID, productLineName, brand, isActive, category, productLineDescription) VALUES (?,?,?,?,?,?)");
            pstmt.setInt(1, product_line_ID);
            pstmt.setString(2, product_line_name);
            pstmt.setString(3, brand);
            if (isActive)
                pstmt.setInt(4, 1);
            else
                pstmt.setInt(4, 0);
            pstmt.setString(5, category);
            pstmt.setString(6, product_line_description);

            // Push Update to Database
            pstmt.executeUpdate();   
   
            // Closing Statements
            pstmt.close();
            conn.close();
            
            return 1;
       
        } catch (SQLException e) {
            return 0;
        }         
    }
    
    public int update_productline(){
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbwarehouse?useTimezone=true&serverTimezone=UTC&user=root&password=12345678");
            
            PreparedStatement pstmt = conn.prepareStatement("UPDATE productline"
                    + "SET productLineName=?, brand=?, isActive =?, category=?, productLineDescription brand WHERE productLineID =?");
            
            pstmt.setString(1, product_line_name);
            pstmt.setString(2, brand);
            if (isActive)
                pstmt.setInt(3, 1);
            else
                pstmt.setInt(3, 0);
            
            pstmt.setString(4, category);
            pstmt.setString(5, product_line_description);
            pstmt.setInt(6, product_line_ID);
            
            pstmt.executeUpdate();   
   
            // Closing Statements
            pstmt.close();
            conn.close();
            
            return 1;
        } catch(SQLException e){
            e.printStackTrace();
            return 0;
        }
    }
    
    public int delete_product_line() {
        try {
            //1. Connect to database.
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbwarehouse?useTimezone=true&serverTimezone=UTC&user=root&password=12345678");

            //2. Delete the product.
            PreparedStatement pstmt = conn.prepareStatement("DELETE FROM productLine WHERE productLineID=?"); //Place DELETE statement.
            pstmt.setInt(1, product_line_ID);

            pstmt.executeUpdate();

            pstmt.close();
            conn.close();

            return 1;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return 0;
        }
    }
    
    public int get_product_lines() {
        //It works.
        try {
            //1. Connect to database.
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbwarehouse?useTimezone=true&serverTimezone=UTC&user=root&password=12345678");

            //Clear field arraylists.
            product_line_IDList.clear();
            product_line_nameList.clear();
            brandList.clear();
            isActiveList.clear();
            categoryList.clear();
            product_line_descriptionList.clear();

            //2. Get warehouses from the database and put them in arraylists.
            PreparedStatement pstmt = conn.prepareStatement("SELECT productLineID, productLineName, brand, isActive, category, productLineDescription FROM productline"); //Place the SQL statement.
            ResultSet rst = pstmt.executeQuery();
            while (rst.next()) {
                product_line_ID = rst.getInt("productLineID");
                product_line_name = rst.getString("productLineName");
                brand = rst.getString("brand");
                isActive = rst.getBoolean("isActive");
                category = rst.getString("category");
                product_line_description = rst.getString("productLineDescription");               

                product_line_IDList.add(product_line_ID);
                product_line_nameList.add(product_line_name);
                brandList.add(brand);
                isActiveList.add(isActive);
                categoryList.add(category);
                product_line_descriptionList.add(product_line_description);
            }

            pstmt.close();
            conn.close();

            return 1;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return 0;
        }
    }
    
    public int get_product_line_IDs() {
        //It works.
        try {
            //1. Connect to database.
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbwarehouse?useTimezone=true&serverTimezone=UTC&user=root&password=12345678");
            //Clear field arraylist.
            product_line_IDList.clear();
            
            //Clear other field arraylists in case.
            product_line_nameList.clear();
            brandList.clear();
            isActiveList.clear();
            categoryList.clear();
            product_line_descriptionList.clear();

            //2. Get products from the database and put them in arraylists.
            PreparedStatement pstmt = conn.prepareStatement("SELECT productLineID FROM productline"); //Place the SQL statement.
            ResultSet rst = pstmt.executeQuery();
            while (rst.next()) {
                product_line_ID = rst.getInt("productLineID");
                product_line_IDList.add(product_line_ID);              
            }

            pstmt.close();
            conn.close();

            return 1;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return 0;
        }
    }
    
    public int get_product_line_record() {
        //It works.
        try {
            //1. Connect to database.
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbwarehouse?useTimezone=true&serverTimezone=UTC&user=root&password=12345678");

            //2. Get warehouses from the database and put them in arraylists.
            PreparedStatement pstmt = conn.prepareStatement("SELECT productLineID, productLineName, brand, isActive, category, productLineDescription FROM productline WHERE productLineID=?"); //Place the SQL statement.
            pstmt.setInt(1, product_line_ID);
            
            ResultSet rst = pstmt.executeQuery();
            while (rst.next()) {
                product_line_name = rst.getString("productLineName");
                brand = rst.getString("brand");
                isActive = rst.getBoolean("isActive");
                category = rst.getString("category");
                product_line_description = rst.getString("productLineDescription");               
            }

            pstmt.close();
            conn.close();

            return 1;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return 0;
        }
    }
    
    public static void main(String args[]) {

    }
    
}
