package productMgmt;

import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.*;

public class product_line {
    
    // Inventory Employee Fields
    public int product_line_ID;
    public String product_line_name;
    public String brand;
    public int isActive = 1;
    public String category;
    public String product_line_description;
    
    // Method: Registration
    public int register_product_line() {
        try {
            
            // Instantiate Connection Variable and Connect to Database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbwarehouse?useTimezone=true&serverTimezone=UTC&user=root&password=12345678");
            
            // MySQL INSERT Statement
            PreparedStatement pstmt = conn.prepareStatement("SELECT MAX(productLineID) + 1 AS newID FROM productline");
            ResultSet rst= pstmt.executeQuery();
            
            // Autogenerated Employee ID
            while(rst.next()) {
                product_line_ID = rst.getInt("newID");
            }
            
            // Assign Values
            pstmt = conn.prepareStatement("INSERT INTO productline (productLineID, productLineName, brand, isActive, category, productLineDescription) VALUES (?,?,?,?,?,?)");
            pstmt.setInt(1, product_line_ID);
            pstmt.setString(2, product_line_name);
            pstmt.setString(3, brand);
            pstmt.setInt(4, isActive);
            pstmt.setString(5, category);
            pstmt.setString(6, product_line_description);

            // Push Update to Database
            pstmt.executeUpdate();   
   
            // Closing Statements
            pstmt.close();
            conn.close();
            
            return 1;
       
        } catch (SQLException e) {
            return 0;
        }         
    }
    
    public static void main(String args[]) {

    }
    
}
